# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MAILTRY.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(424, 665)
        MainWindow.setAccessibleName("")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.receive = QtWidgets.QTabWidget(self.centralwidget)
        self.receive.setGeometry(QtCore.QRect(0, 0, 431, 651))
        self.receive.setObjectName("receive")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.label = QtWidgets.QLabel(self.tab)
        self.label.setGeometry(QtCore.QRect(30, 30, 31, 16))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.tab)
        self.label_2.setGeometry(QtCore.QRect(40, 70, 21, 16))
        self.label_2.setObjectName("label_2")
        self.toaddr = QtWidgets.QPlainTextEdit(self.tab)
        self.toaddr.setGeometry(QtCore.QRect(60, 68, 301, 25))
        self.toaddr.setTabChangesFocus(True)
        self.toaddr.setObjectName("toaddr")
        self.sendbutton = QtWidgets.QPushButton(self.tab)
        self.sendbutton.setGeometry(QtCore.QRect(290, 580, 75, 23))
        self.sendbutton.setObjectName("sendbutton")
        self.attach = QtWidgets.QPlainTextEdit(self.tab)
        self.attach.setGeometry(QtCore.QRect(60, 545, 301, 25))
        self.attach.setTabChangesFocus(True)
        self.attach.setPlainText("")
        self.attach.setObjectName("attach")
        self.content = QtWidgets.QPlainTextEdit(self.tab)
        self.content.setGeometry(QtCore.QRect(60, 150, 301, 381))
        self.content.setStatusTip("")
        self.content.setTabChangesFocus(True)
        self.content.setPlainText("")
        self.content.setOverwriteMode(False)
        self.content.setObjectName("content")
        self.progressBar = QtWidgets.QProgressBar(self.tab)
        self.progressBar.setGeometry(QtCore.QRect(60, 585, 100, 10))
        self.progressBar.setProperty("value", 0)
        self.progressBar.setObjectName("progressBar")
        self.label_3 = QtWidgets.QLabel(self.tab)
        self.label_3.setGeometry(QtCore.QRect(20, 110, 31, 16))
        self.label_3.setObjectName("label_3")
        self.fromaddr = QtWidgets.QPlainTextEdit(self.tab)
        self.fromaddr.setGeometry(QtCore.QRect(60, 28, 301, 25))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.fromaddr.sizePolicy().hasHeightForWidth())
        self.fromaddr.setSizePolicy(sizePolicy)
        self.fromaddr.setTabChangesFocus(True)
        self.fromaddr.setObjectName("fromaddr")
        self.title = QtWidgets.QPlainTextEdit(self.tab)
        self.title.setGeometry(QtCore.QRect(60, 108, 301, 25))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.title.sizePolicy().hasHeightForWidth())
        self.title.setSizePolicy(sizePolicy)
        self.title.setTabChangesFocus(True)
        self.title.setObjectName("title")
        self.label_10 = QtWidgets.QLabel(self.tab)
        self.label_10.setGeometry(QtCore.QRect(10, 150, 41, 16))
        self.label_10.setObjectName("label_10")
        self.label_11 = QtWidgets.QLabel(self.tab)
        self.label_11.setGeometry(QtCore.QRect(13, 547, 41, 20))
        self.label_11.setObjectName("label_11")
        self.AddConnect = QtWidgets.QPushButton(self.tab)
        self.AddConnect.setGeometry(QtCore.QRect(370, 67, 38, 26))
        self.AddConnect.setObjectName("AddConnect")
        self.AddAttach = QtWidgets.QPushButton(self.tab)
        self.AddAttach.setGeometry(QtCore.QRect(370, 545, 38, 26))
        self.AddAttach.setObjectName("AddAttach")
        self.receive.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.groupBox_2 = QtWidgets.QGroupBox(self.tab_2)
        self.groupBox_2.setGeometry(QtCore.QRect(10, 10, 391, 351))
        self.groupBox_2.setObjectName("groupBox_2")
        self.listMail = QtWidgets.QListWidget(self.groupBox_2)
        self.listMail.setGeometry(QtCore.QRect(20, 30, 261, 311))
        self.listMail.setObjectName("listMail")
        self.showMail = QtWidgets.QPushButton(self.groupBox_2)
        self.showMail.setGeometry(QtCore.QRect(300, 280, 75, 23))
        self.showMail.setObjectName("showMail")
        self.maildetail = QtWidgets.QPushButton(self.groupBox_2)
        self.maildetail.setGeometry(QtCore.QRect(300, 320, 75, 23))
        self.maildetail.setObjectName("maildetail")
        self.readspeed = QtWidgets.QProgressBar(self.groupBox_2)
        self.readspeed.setGeometry(QtCore.QRect(300, 260, 90, 10))
        self.readspeed.setProperty("value", 0)
        self.readspeed.setObjectName("readspeed")
        self.groupBox_3 = QtWidgets.QGroupBox(self.tab_2)
        self.groupBox_3.setGeometry(QtCore.QRect(10, 360, 391, 331))
        self.groupBox_3.setObjectName("groupBox_3")
        self.mailcontent = QtWidgets.QTextBrowser(self.groupBox_3)
        self.mailcontent.setGeometry(QtCore.QRect(20, 21, 351, 221))
        self.mailcontent.setObjectName("mailcontent")
        self.receive.addTab(self.tab_2, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.tab_3.setObjectName("tab_3")
        self.groupBox = QtWidgets.QGroupBox(self.tab_3)
        self.groupBox.setGeometry(QtCore.QRect(10, 350, 401, 211))
        self.groupBox.setObjectName("groupBox")
        self.autoreply = QtWidgets.QPlainTextEdit(self.groupBox)
        self.autoreply.setGeometry(QtCore.QRect(20, 60, 361, 141))
        self.autoreply.setObjectName("autoreply")
        self.autoreplay_check = QtWidgets.QCheckBox(self.groupBox)
        self.autoreplay_check.setGeometry(QtCore.QRect(20, 30, 51, 20))
        self.autoreplay_check.setObjectName("autoreplay_check")
        self.save_info = QtWidgets.QPushButton(self.tab_3)
        self.save_info.setGeometry(QtCore.QRect(240, 580, 75, 23))
        self.save_info.setObjectName("save_info")
        self.not_save_info = QtWidgets.QPushButton(self.tab_3)
        self.not_save_info.setGeometry(QtCore.QRect(330, 580, 75, 23))
        self.not_save_info.setObjectName("not_save_info")
        self.groupBox_4 = QtWidgets.QGroupBox(self.tab_3)
        self.groupBox_4.setGeometry(QtCore.QRect(10, 20, 401, 191))
        self.groupBox_4.setObjectName("groupBox_4")
        self.label_5 = QtWidgets.QLabel(self.groupBox_4)
        self.label_5.setGeometry(QtCore.QRect(30, 150, 31, 16))
        self.label_5.setObjectName("label_5")
        self.label_7 = QtWidgets.QLabel(self.groupBox_4)
        self.label_7.setGeometry(QtCore.QRect(310, 150, 31, 16))
        self.label_7.setObjectName("label_7")
        self.s_ssl_check = QtWidgets.QCheckBox(self.groupBox_4)
        self.s_ssl_check.setGeometry(QtCore.QRect(265, 110, 41, 16))
        self.s_ssl_check.setObjectName("s_ssl_check")
        self.smtpedit = QtWidgets.QLineEdit(self.groupBox_4)
        self.smtpedit.setGeometry(QtCore.QRect(60, 108, 191, 20))
        self.smtpedit.setObjectName("smtpedit")
        self.password = QtWidgets.QLineEdit(self.groupBox_4)
        self.password.setGeometry(QtCore.QRect(60, 68, 191, 20))
        self.password.setObjectName("password")
        self.p_ssl_check = QtWidgets.QCheckBox(self.groupBox_4)
        self.p_ssl_check.setGeometry(QtCore.QRect(265, 150, 41, 16))
        self.p_ssl_check.setObjectName("p_ssl_check")
        self.label_6 = QtWidgets.QLabel(self.groupBox_4)
        self.label_6.setGeometry(QtCore.QRect(310, 110, 31, 16))
        self.label_6.setObjectName("label_6")
        self.username = QtWidgets.QLineEdit(self.groupBox_4)
        self.username.setGeometry(QtCore.QRect(60, 28, 191, 20))
        self.username.setObjectName("username")
        self.pop3edit = QtWidgets.QLineEdit(self.groupBox_4)
        self.pop3edit.setGeometry(QtCore.QRect(60, 148, 191, 20))
        self.pop3edit.setObjectName("pop3edit")
        self.s_port = QtWidgets.QLineEdit(self.groupBox_4)
        self.s_port.setGeometry(QtCore.QRect(340, 108, 51, 20))
        self.s_port.setObjectName("s_port")
        self.p_port = QtWidgets.QLineEdit(self.groupBox_4)
        self.p_port.setGeometry(QtCore.QRect(340, 148, 51, 20))
        self.p_port.setObjectName("p_port")
        self.label_4 = QtWidgets.QLabel(self.groupBox_4)
        self.label_4.setGeometry(QtCore.QRect(30, 110, 31, 16))
        self.label_4.setObjectName("label_4")
        self.label_8 = QtWidgets.QLabel(self.groupBox_4)
        self.label_8.setGeometry(QtCore.QRect(20, 30, 41, 16))
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(self.groupBox_4)
        self.label_9.setGeometry(QtCore.QRect(20, 70, 41, 16))
        self.label_9.setObjectName("label_9")
        self.groupBox_5 = QtWidgets.QGroupBox(self.tab_3)
        self.groupBox_5.setGeometry(QtCore.QRect(10, 230, 401, 101))
        self.groupBox_5.setObjectName("groupBox_5")
        self.RunWhenOpenCheck = QtWidgets.QCheckBox(self.groupBox_5)
        self.RunWhenOpenCheck.setGeometry(QtCore.QRect(30, 30, 71, 16))
        self.RunWhenOpenCheck.setObjectName("RunWhenOpenCheck")
        self.NewMailCheck = QtWidgets.QCheckBox(self.groupBox_5)
        self.NewMailCheck.setGeometry(QtCore.QRect(30, 60, 121, 21))
        self.NewMailCheck.setObjectName("NewMailCheck")
        self.checkTime = QtWidgets.QSpinBox(self.groupBox_5)
        self.checkTime.setGeometry(QtCore.QRect(150, 60, 42, 22))
        self.checkTime.setMinimum(1)
        self.checkTime.setMaximum(20)
        self.checkTime.setObjectName("checkTime")
        self.label_12 = QtWidgets.QLabel(self.groupBox_5)
        self.label_12.setGeometry(QtCore.QRect(200, 63, 31, 16))
        self.label_12.setObjectName("label_12")
        self.receive.addTab(self.tab_3, "")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.sendbutton.clicked.connect(self.sendMail)
        self.AddConnect.clicked.connect(self.showConnect)
        self.AddAttach.clicked.connect(self.showFiles)
        self.showMail.clicked.connect(self.listAllMail)
        self.maildetail.clicked.connect(self.showMailDetail)
        self.save_info.clicked.connect(self.saveInfo)
        self.not_save_info.clicked.connect(self.saveCancel)
        MainWindow.setFixedSize(MainWindow.width(), MainWindow.height())

        self.retranslateUi(MainWindow)
        self.receive.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.fromaddr, self.toaddr)
        MainWindow.setTabOrder(self.toaddr, self.title)
        MainWindow.setTabOrder(self.title, self.content)
        MainWindow.setTabOrder(self.content, self.attach)
        MainWindow.setTabOrder(self.attach, self.sendbutton)
        MainWindow.setTabOrder(self.sendbutton, self.receive)
        MainWindow.setTabOrder(self.receive, self.showMail)
        MainWindow.setTabOrder(self.showMail, self.maildetail)
        MainWindow.setTabOrder(self.maildetail, self.listMail)
        MainWindow.setTabOrder(self.listMail, self.mailcontent)
        MainWindow.setTabOrder(self.mailcontent, self.autoreply)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "EasyMail"))
        self.label.setText(_translate("MainWindow", "From"))
        self.label_2.setText(_translate("MainWindow", "To"))
        self.sendbutton.setText(_translate("MainWindow", "Send"))
        self.label_3.setText(_translate("MainWindow", "Title"))
        self.label_10.setText(_translate("MainWindow", "Content"))
        self.label_11.setText(_translate("MainWindow", "Attach"))
        self.AddConnect.setText(_translate("MainWindow", "Add"))
        self.AddAttach.setText(_translate("MainWindow", "Add"))
        self.receive.setTabText(self.receive.indexOf(self.tab), _translate("MainWindow", "Send Mail"))
        self.groupBox_2.setTitle(_translate("MainWindow", "Mail list"))
        self.showMail.setText(_translate("MainWindow", "Recent mail"))
        self.maildetail.setText(_translate("MainWindow", "Mail detail"))
        self.groupBox_3.setTitle(_translate("MainWindow", "Mail content"))
        self.receive.setTabText(self.receive.indexOf(self.tab_2), _translate("MainWindow", "Receive Mail"))
        self.groupBox.setTitle(_translate("MainWindow", "自动回复"))
        self.autoreplay_check.setText(_translate("MainWindow", "Open"))
        self.save_info.setText(_translate("MainWindow", "Save"))
        self.not_save_info.setText(_translate("MainWindow", "Cancel"))
        self.groupBox_4.setTitle(_translate("MainWindow", "用户信息"))
        self.label_5.setText(_translate("MainWindow", "POP3"))
        self.label_7.setText(_translate("MainWindow", "PORT"))
        self.s_ssl_check.setText(_translate("MainWindow", "SSL"))
        self.p_ssl_check.setText(_translate("MainWindow", "SSL"))
        self.label_6.setText(_translate("MainWindow", "PORT"))
        self.label_4.setText(_translate("MainWindow", "SMTP"))
        self.label_8.setText(_translate("MainWindow", "用户名"))
        self.label_9.setText(_translate("MainWindow", "授权码"))
        self.groupBox_5.setTitle(_translate("MainWindow", "其他设置"))
        self.RunWhenOpenCheck.setText(_translate("MainWindow", "开机启动"))
        self.NewMailCheck.setText(_translate("MainWindow", "检测新邮件：每隔"))
        self.label_12.setText(_translate("MainWindow", "分钟"))
        self.receive.setTabText(self.receive.indexOf(self.tab_3), _translate("MainWindow", "Setting"))

